### ISSUE TITLE
`mastra.getTool` does not infer output

### ISSUE THREAD

**Issue by austinm911** [mastra-ai/mastra#954] opened 2024-12-08 20:09 UTC
Appears that get tool does not infer its return types

```ts
export const marketTrendTool = createTool({
	label: 'Market Trend Research',
	schema: z.object({
		sector: sectorSchema,
	}),
	outputSchema: z.object({
		growthRate: z.number(),
		marketSize: z.string(),
		hotSubsectors: z.array(z.string()),
	}),
	description: 'Provides mock market trend data for startup sectors',
	executor: async ({ data: { sector } }) => {
		console.log(`Simulating market trend research for ${sector}`)
		const result = marketTrendData[sector]
		console.log(`Market Trend Tool Result: ${JSON.stringify(result)}`)
		return result
	},
})

const marketTrendStep = new Step({
	id: 'marketTrend',
	inputSchema: z.object({
		sector: sectorSchema,
	}),
	action: async ({ data, runId }) => {
		console.log(`Running market trend step for ${data.sector}`)
		const marketTrendTool = mastra.getTool('marketTrendTool')
		const result = await marketTrendTool.execute({ sector: data.sector })
		return result
	},
})
```
<img width="966" alt="image" src="https://github.com/user-attachments/assets/852d5998-1c46-446b-b66d-d7cd3be32610">

<img width="1595" alt="image" src="https://github.com/user-attachments/assets/ced6a7c1-341c-440b-870a-4a547562ab17">

**Comment by abhiaiyer91** [comment] 2024-12-08 20:28
Nice another great catch, thank you! Will address this.

We are iterating on Workflows, so the thing you are trying to do here will become easier and less verbose. If this is blocking you, for now you can just call your function directly inside a step action vs getting it from the tool registry.


```
export function marketTrendSvcApi() {}

export const marketTrendTool = createTool({
	label: 'Market Trend Research',
	schema: z.object({
		sector: sectorSchema,
	}),
	outputSchema: z.object({
		growthRate: z.number(),
		marketSize: z.string(),
		hotSubsectors: z.array(z.string()),
	}),
	description: 'Provides mock market trend data for startup sectors',
	executor: async ({ data: { sector } }) => {
		console.log(`Simulating market trend research for ${sector}`)
		const result = marketTrendSvcApi(marketTrendData[sector])
		console.log(`Market Trend Tool Result: ${JSON.stringify(result)}`)
		return result
	},
})

const marketTrendStep = new Step({
	id: 'marketTrend',
	inputSchema: z.object({
		sector: sectorSchema,
	}),
	action: async ({ data, runId }) => {
		console.log(`Running market trend step for ${data.sector}`)
		const result = await marketTrendSvcApi({ sector: data.sector })
		return result
	},
})
```

in the future you'll be able to execute tool calls as steps.

**Comment by TheIsrael1** [comment] 2024-12-08 21:31
Hi @austinm911 , I tried to reproduce this and I do get the return type inferred.
![CleanShot 2024-12-08 at 22 29 37@2x](https://github.com/user-attachments/assets/85d1aec6-3924-413b-9890-36ee11f42580)
I do believe it didn't work until recently. Pls do try it out with the latest @mastra/core alpha version.

**Comment by austinm911** [comment] 2024-12-09 20:53
@TheIsrael1 i can confirm it works on .24 now. But i'm now noticing that the intellisense does not work when other packages are installed. I made a new repo and it works with no other packages installed. But after adding zod, intellisense stops working. 5.5.4 and 5.7.2 TS both have the issue

![image](https://github.com/user-attachments/assets/2fd48783-eb38-425a-9faf-68b2197789b1)

**Comment by abhiaiyer91** [comment] 2024-12-11 01:23
I updated all our packages to use the new zod version 3.24.0. We were pinned at 3.23.7 due to some weird Zod ts error resolved in 3.24.0. Maybe that fixes this issue?

**Comment by austinm911** [comment] 2024-12-11 08:00
@abhiaiyer91 seems to have fixed it based on my quick look

**Comment by abhiaiyer91** [comment] 2024-12-11 15:46
Will close this. Thank you for catching this!

**Closed by abhiaiyer91** 2024-12-11 15:46 UTC
